# Common Configuration for all microservices

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/library-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://library-keycloak:8080/realms/library-realm/protocol/openid-connect/certs

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=true

# Eureka Client configuration
eureka.client.service-url.defaultZone=http://admin:admin123@eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# Common Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
